[[repos]]
repo = "builtin"
hooks = [
    { id = "trailing-whitespace", exclude = '^tests/(testdata|missing_functionality)/.*\.html$' },
    { id = "end-of-file-fixer", exclude = '^tests/(testdata|missing_functionality)/.*\.html$' },
    { id = "check-yaml" },
    { id = "check-toml" },
    { id = "check-json" },
    { id = "check-merge-conflict" },
    { id = "mixed-line-ending" },
    { id = "check-case-conflict" },
    { id = "check-illegal-windows-names" },
    { id = "fix-byte-order-marker" },
    { id = "check-executables-have-shebangs" },
    { id = "check-shebang-scripts-are-executable" },
    { id = "check-vcs-permalinks" },
    { id = "detect-private-key" },
]

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"  # frozen: v6.0.0
hooks = [
    { id = "debug-statements" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "e8f7d69b957a30acb2c875078d5fd012de24b64c"  # frozen: v0.16.7
hooks = [
    { id = "ruff-check", args = ["--fix", "--exit-non-zero-on-fix"] },
]
