name: scheduled tests

on:
  schedule:
    # Run tests weekly on Sundays at 5:47 UTC.
    # This might help us us detecting unexpected breakage due to changes in
    # 3rd-party dependencies. GitHub only triggers this for the default branch.
    - cron: '47 5 * * 0'

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
